config/routes.rb
Rails.application.routes.draw do

  get 'static/home'

  get 'dashboard/index'
  get 'dashboard/admin_dashboard'
  post 'dashboard/admin_dashboard'
  get 'dashboard/new_form'
  post 'dashboard/new_create'
  get 'dashboard/calendarDates'
  get 'dashboard/calendarEvents'
  get 'dashboard/dayEvents'

  post 'users/update_address'
  post 'users/update_email'
  post 'users/update_password'
  post 'users/update_phone'

  post 'classrooms/setAttendance'
  post 'classrooms/setGrades'
  get 'classrooms/getClassroom'
  post 'classrooms/editClassroom'
  post 'classrooms/sendEmail'
  get 'classrooms/attendanceList'
  get 'classrooms/gradesList'

  devise_for :users, 
    :path => '',
    :path_names => {
      :sign_in  => "login",
      :sign_out => "logout",
      :sign_up  => "register"
    }

  root 'static#home'

  resources :users, :classrooms, :assignments, :events, :submissions

end

app/controllers/dashboard_controller.rb
# voe

class DashboardController < ApplicationController
	before_action :require_login
	def index
		if current_user.account_type === "Admin"
			render 'admin_dashboard'
		else
			@classrooms = current_user.account.classrooms
			render 'dashboard'
		end
	end

	def admin_dashboard
		@infoType = params[:infoType]
		case params[:infoType]
			when "Students"
				@info = Student.all
			when "Teachers"
				@info = Teacher.all
			when "Classrooms"
				@info = Classroom.all
		end
		render 'admin_dashboard'
	end

	def new_form
		@infoType = params[:infoType]
		render 'admin_dashboard_new'
	end

	def new_create
		@infoType = params[:infoType]
		case params[:infoType]
			when "Students"
				resource, pass = User.create_account_random_pass(
					"Student",
					{
					:first_name => params[:firstname],
					:middle_name => params[:middlename],
					:last_name => params[:lastname],
					:identifier => params[:id],
					:school => current_user.school
					})
			when "Teachers"
				resource, pass = User.create_account_random_pass(
					"Teacher",
					{
					:first_name => params[:firstname],
					:middle_name => params[:middlename],
					:last_name => params[:lastname],
					:identifier => params[:id],
					:school => current_user.school
					})
			when "Classrooms"
				resource = classroom = Classroom.create(
					:name => params[:name],
					:time => params[:time],
					:location => params[:location],
					:description => params[:description],
					:student_capacity => params[:capacity],
					:school => current_user.school
					)
				if user = User.find_by_identifier(params[:teacher])
					classroom.teachers << user.account
				end
				params[:students].split(',').map(&:strip).each do |student|
					if user = User.find_by_identifier(student)
						classroom.students << user.account
					end
				end
		end
		if resource && resource.save
			redirect_to dashboard_admin_dashboard_path(infoType: @infoType),
				:notice => "Resource successfully created"
		else
			redirect_to dashboard_new_form_path(infoType: @infoType),
				:notice => "An error occurred, try again"
		end
	end

	def calendarDates
		year = params[:year].to_i
		month = params[:month].to_i
		date = params[:date].to_i
		monthString = Date.new(year, month).strftime("%B")
		dateList = Event.get_dates_for_month(year, month)
		render json: {year: year, month: month, date: date, monthString: monthString, dates: dateList}
	end

	def calendarEvents
		year = params[:year].to_i
		month = params[:month].to_i
		eventList = Event.get_date_range(current_user.account, Event.calendar_first_date(year, month), Event.calendar_last_date(year, month))
		render json: {year: year, month: month, events: eventList}
	end

	def dayEvents
		year = params[:year].to_i
		month = params[:month].to_i
		day = params[:day].to_i
		date = DateTime.new(year, month, day)
		eventList = Event.get_day(current_user.account, date)
		render json: {date: date, events: eventList}
	end

	private

	def require_login
	    unless user_signed_in?
	      flash[:error] = "please log in"
	      redirect_to new_user_session_path
	    end
	end

end

app/helpers/dashboard_helper.rb
module DashboardHelper

end

app/views/dashboard/partials/_calendar_feed.html.erb
<div class="col-sm-7">
	<div id="calendar" class="container-fluid calendar">
		<div id="calendar-header" class="row calendar-header">
			<div class="calendar-header-left">
				<div class="btn-group">
					<button type="button" class="btn btn-default" onclick="previousMonth()">prev</button>
					<button type="button" class="btn btn-default" onclick="setCalendarToToday()">today</button>
					<button type="button" class="btn btn-default" onclick="nextMonth()">next</button>
				</div>
			</div>
			<div class="calendar-header-middle">
				<h2 id="month-label" class="month-label">Month</h2>
			</div>
			<div class="calendar-header-right">
  				<button class="btn btn-sm new-event-button" onclick="toggleModal('newEventModal')">+</button>
			</div>
		</div>
		<div class="row calendar-week-header">
			<div class="calendar-day day-label">sun</div>
	        <div class="calendar-day day-label">mon</div>
	      	<div class="calendar-day day-label">tue</div>
	      	<div class="calendar-day day-label">wed</div>
	      	<div class="calendar-day day-label">thu</div>
	      	<div class="calendar-day day-label">fri</div>
	      	<div class="calendar-day day-label">sat</div>
	    </div>
		
		<div id="calendar-content">
		</div>

	</div>
</div>
<script>
	var selectedMonth = new Date();
	var dateSelected = false;
	$(document).ready(function() {
    	setCalendarToToday();
	});
</script>

app/views/dashboard/partials/_day_info_feed.html.erb
<div id="day-info-feed-panel" class="col-sm-3">
	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 id="day-feed-panel-title" class="panel-title center-text"><!-- Generated by AJAX --></h3>
	  </div>
	  <div id="day-feed-panel-body" class="panel-body">
	  	<!-- Generated by AJAX -->
	  </div>
	</div>
</div>

app/views/dashboard/partials/_new_event_modal.html.erb
<!-- @author: voe -->

<div class="modal" id="newEventModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title center">New Event</h2>
      </div>
      <div class="modal-body">
        <h4 class="center">create a newEvent</h4>
        <%= form_tag events_path do %>
          <div>
            <%= label_tag(:name, "name:") %>
            <%= text_field_tag(:name, nil, required: true) %>
          </div>
          <div>
            <%= label_tag(:description, "description:") %>
            <%= text_area_tag(:description, "add a description") %>
          </div>
          <div>
            <%= label_tag(:date, "date:") %>
            <%= date_field(:due, "date", required: true) %>
          </div>
          <div>
            <%= label_tag(:due_time, "due time:") %>
            <%= time_field(:due, "time", value: "23:59", required: true) %>
          </div>
          <br>
          <%= submit_tag("create event") %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" onclick="toggleModal('newEventModal')">Close</button>
      </div>
    </div>
  </div>
</div>