config/routes.rb
Rails.application.routes.draw do

  get 'static/home'

  get 'dashboard/index'
  get 'dashboard/admin_dashboard'
  post 'dashboard/admin_dashboard'
  get 'dashboard/new_form'
  post 'dashboard/new_create'
  get 'dashboard/calendarDates'
  get 'dashboard/calendarEvents'
  get 'dashboard/dayEvents'

  post 'users/update_address'
  post 'users/update_email'
  post 'users/update_password'
  post 'users/update_phone'

  post 'classrooms/setAttendance'
  post 'classrooms/setGrades'
  get 'classrooms/getClassroom'
  post 'classrooms/editClassroom'
  post 'classrooms/sendEmail'
  get 'classrooms/attendanceList'
  get 'classrooms/gradesList'

  devise_for :users, 
    :path => '',
    :path_names => {
      :sign_in  => "login",
      :sign_out => "logout",
      :sign_up  => "register"
    }

  root 'static#home'

  resources :users, :classrooms, :assignments, :events, :submissions

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :classroom
  has_many :submissions


  has_one :event, :as => :owner, :dependent => :destroy

  before_validation :default_values, on: :create
  after_create :create_submissions
  after_create :create_event

  validates :teacher,      presence: true
  validates :classroom,    presence: true
  validates :name,         presence: true
  validates :due,          presence: true

  def get_submission(student_id)
    submissions.find_by_student_id(student_id)
  end

  private

  def create_submissions
    classroom.students.each {|s| submissions.create(:student_id => s.id)}
  end

  def create_event
    self.event = Event.create(
        :name => name,
        :description => description,
        :startime => due,
        :endtime => due,
        :classroom_id => classroom_id
    )
  end

  def default_values
    self.max_points ||= 0
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
	before_action :require_login

	def new
	end

	def create
		date = nil
		if !params[:due][:date].empty? and !params[:due][:time].empty?
			dateString = params[:due][:date] + " " + params[:due][:time]
			date = DateTime.strptime(dateString, '%Y-%m-%d %H:%M')
		end

		assignmentParams = {
			"teacher_id" => params[:teacher_id],
			"classroom_id" => params[:classroom_id],
			"max_points" => params[:max_points],
			"name" => params[:name],
			"description" => params[:description],
			"due" => date,
		}

		logger.debug "------------------assignmentParams2: #{assignmentParams}"

		@assignment = Assignment.new(assignmentParams)
		#@assignment = Assignment.create(assignment_params) #currently does not work

		if @assignment.save
			redirect_to @assignment
		else
			render "classrooms/show"
		end
	end

	def index
	end

	def show
		@assignment = Assignment.find(params[:id])
		@classroom = Classroom.find(@assignment.classroom_id)
		if current_user.account_type == "Student"
			@submission = current_user.account.submission(@assignment.id)
		end
	end

	def update
	end

	def destroy
	end

	private

	def assignment_params #THIS CURRENTLY DOES NOT WORK
		params.require(:teacher_id)
		params.require(:classroom_id)
		params.require(:name)
		params.require(:due)
	end

	def require_login
	    unless user_signed_in?
	      flash[:error] = "please log in"
	      redirect_to new_user_session_path
	    end
	end

end

app/helpers/assignments_helper.rb
module AssignmentsHelper

	def formatDate(date)
		return date.strftime("%B %d, %Y at %l:%M %P")
	end

end

app/views/assignments/partials/_new_assignment.html.erb
<span class="pull-right">
  <button class="btn btn-sm" onclick="toggleModal('newAssignmentModal')">
    new assignment
  </button>
</span>
<div class="modal" id="newAssignmentModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title center">Create New Assignment</h2>
      </div>
      <div class="modal-body">
        <%= form_tag url_for(assignments_path) do %>
          
          <%= hidden_field_tag(:classroom_id, @classroom.id) %>
          <%= hidden_field_tag(:teacher_id, @classroom.teachers.first.id) %>

          <div>
            <%= label_tag(:name, "name:") %>
            <%= text_field_tag(:name, nil, required: true) %>
          </div>
          <br>
          <div>
            <%= label_tag(:description, "description:") %>
            <%= text_area_tag(:description, nil) %>
          </div>
          <br>
          <div>
            <%= label_tag(:max_points, "total possible points:") %>
            <%= number_field_tag(:max_points, in: 1..Float::INFINITY, step: 0.5) %>
          </div>
          <br>
          <div>
            <%= label_tag(:due_date, "due date:") %>
            <%= date_field(:due, "date", required: true) %>
          </div>
          <br>
          <div>
            <%= label_tag(:due_time, "due time:") %>
            <%= time_field(:due, "time", value: "23:59", required: true) %>
          </div>
          <br>
          <%= submit_tag("create assignment") %>

      <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" onclick="toggleModal('newAssignmentModal')">Close</button>
      </div>
    </div>
  </div>
</div>