config/routes.rb
Rails.application.routes.draw do

  get 'static/home'

  get 'dashboard/index'
  get 'dashboard/admin_dashboard'
  post 'dashboard/admin_dashboard'
  get 'dashboard/new_form'
  post 'dashboard/new_create'
  get 'dashboard/calendarDates'
  get 'dashboard/calendarEvents'
  get 'dashboard/dayEvents'

  post 'users/update_address'
  post 'users/update_email'
  post 'users/update_password'
  post 'users/update_phone'

  post 'classrooms/setAttendance'
  post 'classrooms/setGrades'
  get 'classrooms/getClassroom'
  post 'classrooms/editClassroom'
  post 'classrooms/sendEmail'
  get 'classrooms/attendanceList'
  get 'classrooms/gradesList'

  devise_for :users, 
    :path => '',
    :path_names => {
      :sign_in  => "login",
      :sign_out => "logout",
      :sign_up  => "register"
    }

  root 'static#home'

  resources :users, :classrooms, :assignments, :events, :submissions

end

app/views/layouts/_navbar.html.erb
<!-- @author: voe, dlaroue -->
<!-- @author: voe, elewis, jdefond -->
<!-- partial for the navbar -->

<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div>
    
    <% if user_signed_in? %>

      <div class="navbar-header">
        <%= link_to image_tag("sc_logo_white.png", height: 50), dashboard_index_path %>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li> 
          <%= link_to "profile", "/users/show", id: "profile-path" %>
        </li>
        <li>
          <%= link_to "log out", destroy_user_session_path, id: "logout-btn" %>
        </li>
      </ul>

    <% else %>
      <div class="navbar-header">
        <%= link_to image_tag("sc_logo_white.png", height: 50), root_path %>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                about <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                  <li><a href="#about-home">Home</a></li>
                  <li><a href="#about-students">Students</a></li>
                  <li><a href="#about-teachers">Teachers</a></li>
                  <li><a href="#about-administrators">Administrators</a></li>
              </ul>
            </li>
            <li>
          <%= link_to "contacts", root_path %>
        </li>
        <li>
          <%= link_to "log in", new_user_session_path, id: "login-menu" %>
        </li>
      </ul>

    <% end %> 


  </div>
</div>

app/views/layouts/_side_admin_menu.html.erb
<!-- @author: mchuang -->
<!-- partial for the side menu on the admin dashboard -->

<div class="col-sm-2 menu-left">
    <div class="profile-display">
        <div class="profile-panel">
            <a href="/users/show">
              <img class="thumbnail user-image" src="http://simpleicon.com/wp-content/uploads/user1-150x150.png">
              <h4><%= current_user.identifier %></h4>
            </a>
        </div>
    </div>

    <div class="adminlist">
        <%= link_to dashboard_admin_dashboard_path(infoType: "Classrooms"), id: "classrooms-tab" do %>
            <div class="row classlist-item">
                <h3>Classrooms</h3>
            </div>
        <% end %>
        <%= link_to dashboard_admin_dashboard_path(infoType: "Teachers"), id: "teachers-tab"  do %>
            <div class="row classlist-item">
                <h3>Teachers</h3>
            </div>
        <% end %>
        <%= link_to dashboard_admin_dashboard_path(infoType: "Students"), id: "students-tab"  do %>
            <div class="row classlist-item">
                <h3>Students</h3>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/_side_menu.html.erb
<!-- @author: voe, dlaroue -->
<!-- partial for the side menu of the dashboard for students and teachers -->

<div class="col-sm-2 menu-left">
    <div id="profile-display" class="profile-display">
    	<div class="profile-panel">
			<a href="/users/show">
		      <img class="thumbnail user-image" src="http://simpleicon.com/wp-content/uploads/user1-150x150.png">
              <h4><%= current_user.identifier %></h4>
		    </a>
	    </div>
    </div>

    <div id="classlist" class="classlist">
    	<hr>

    	<% if @classroom.nil? %>
    		<div class="row classlist-item active">
    			<h3>dashboard</h3>
    		</div>
    	<% else %>
    		<%= link_to dashboard_index_path do %>
				<div class="row classlist-item">
    				<h3>dashboard</h3>
    			</div>
			<% end %>
		<% end %>

    	<hr>

    	<% @classrooms.each do |t, a| %>

    		<% if @classroom and @classroom.name == t.name %>
    			<div class="row classlist-item active">
    				<h3><%= t.name %></h3>
    			</div>
    		<% else %>
				<%= link_to classroom_path(t), id: t.name do %>
					<div class="row classlist-item">
						<h3><%= t.name %></h3>
					</div>
				<% end %>
    		<% end %>
			<hr>

    	<%end%>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  	<title>Schoolcentral</title>
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>
  	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
  	<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"> </script>
</head>
<body>

	<%= render "layouts/navbar" %>
	
	<%= yield %>
	
</body>
</html>